# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - name: Checkout the latest code
        uses: actions/checkout@v3
        
      - name: Docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Pull grafana/k6 docker images
        run: sudo docker pull grafana/k6

      - name: run the K6 scripts
        run: sudo docker run -it  --name k6 --user "$(id -u $USER)" -v $(pwd):/src --workdir "/src" -i grafana/k6 run /src/scripts/test.js  


      - name: check report files
        continue-on-error: true
        run: |
          ls -a
          cd result && ls -a
        
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: result

      -name: Remove the k6 container
       if: always()
       run: |
        sudo docker stop k6 && sudo docker rm k6    
